### ISSUE TITLE
Set up automatic deployments

### ISSUE THREAD

**Issue by albertyw** [almlab/www#1]

**Comment by swo** [comment]
this would be totally sweet. right now i have to log in to Athena and run "git pull" and "make". i could learn, but i don't know if the learning-cost :: profit ratio would work out. thoughts?

**Comment by albertyw** [comment]
Simplest thing would be to set up a Deploy Key on this repo, add it to Athena, create a shell script to run the deploy, and set Github to call the script, possibly through a CI system like Codeship.

**Comment by swo** [comment]
Just had a stab at this. MIT's dialup thing is tricky: you need to enter your password to get Kerberos tickets, which in turn lets you do things like change files. Aside from switching servers, is there a way around this?

**Comment by albertyw** [comment]
Yeah, I see that.  Codeship would need to be able to log into athena do update the website which would require giving Codeship authentication data which would be a security risk.  

An easier and jankier solution that I've done on other websites would be for Codeship to hit some special web page and have the web page run a bash script to update itself.  It would be ~5 lines of PHP code and the bash script would just be a `git pull`.  Probably would also need to run https://scripts.mit.edu/faq/31/can-my-scripts-write-data-somewhere to make sure the bash script will work.

**Comment by swo** [comment]
Done.
