### ISSUE TITLE
Fix background of MIT logo

### ISSUE THREAD

**Issue by albertyw** [almlab/www#2]
When you mouse over the MIT logo on the upper-right hand corner of each page, a weird black background appears.  Tested in Chrome and Firefox.

**Comment by cduvallet** [comment]
YES I finally figured this out!! 😂 

Commit [5b1ce8477c3beca4a4066636219e103e61344e7d](https://github.com/almlab/www/commit/5b1ce8477c3beca4a4066636219e103e61344e7d) and [e78dc50228499199663dce7ef3655adbe328332a](https://github.com/almlab/www/commit/e78dc50228499199663dce7ef3655adbe328332a) fix this by adding a new type of `:hover` specifier in the `almLinks.css` specifications:

```
a.img_link:hover {
    background-color: #fff;
}
```

Then I just added `class="img_link"` to the URL declaration for all linked images, including the MIT logo in the main html template.

(I know nothing about html/css so even though my terminology is probably wrong, I hope this can still be useful to future admins!)

**Comment by cduvallet** [comment]
JK, I also had to go in and force re-make the site from scratch because editing `almSite.template.html` did not trigger a re-make.

```
ssh duvallet@athena.dialup.mit.edu
cd /afs/athena.mit.edu/org/a/almlab/
touch xml/*.xml
make
```

This seems to have worked.
